### ISSUE TITLE
Publish test1.0 branch to npm

### ISSUE THREAD

**Issue by w8r** [Norkart/Leaflet-MiniMap#108]
Can you please publish the beta-version of `leaflet-1.0.x` support on npm?

**Comment by robpvn** [comment]
Reading http://leafletjs.com/2015/10/14/leaflet-1.0-beta2-released.html i just decided to go ahead and release it onto NPM the normal way because everybody probably uses 1.0 by now anyway and I didn't have to make any changes for compatability anyway. So just use v3.2.0 or 3.1.1, they both work with the 1.0 beta.

**Comment by w8r** [comment]
I wouldn't say everyone uses leaflet-1.0, nor will use it soon enough, cause it has breaking changes, but thanks anyway. You can also publish 1.0.0 compatible version as _not default_ at npm - the way leaflet publishes now.

**Comment by w8r** [comment]
```shell
npm publish && npm tag leaflet-minimap@3.1.1 latest
```
for example

**Comment by robpvn** [comment]
Ooh, nice trick. I'll do that then!
