### ISSUE TITLE
collapsed minimap not being displayed properly on mobile devices (Maps Marker Pro issue?)

### ISSUE THREAD

**Issue by robertharm** [Norkart/Leaflet-MiniMap#111]
Hi Rob,

I plan to release Maps Marker Pro v2.7 on April 30th and now found that there is an issue with minimap plugin on mobile devices: if I set the minimap to start minimized at https://www.mapsmarker.com/dev/pro/2016/04/03/v2-7-preview/, it is not displayed properly on mobile devices (checked on latest iOS and Android/Firefox):

![minimap-issue](https://cloud.githubusercontent.com/assets/158669/14764012/883eba76-09a8-11e6-854d-2b9c95087d1d.jpg)

If I set minimap to start expanded, it works properly on mobile devices (collapsing and re-expanding it also works fine).

I uploaded your current git repo to my server and the startminimised-example at http://www.mapsmarker.com/dev/pro/mm/example/example_startminimised.html works properly even on mobile devices. As using exactly your distribution without any modification on my dev server didnt have any effect, there must be some other conflict - perhaps with other leaflet plugins that are also used.

If you have any hint why your minimap addon does not work together with Maps Marker Pro, that would really be appreciated!
best,

Robert

**Comment by robpvn** [comment]
The way it looks in the screenshot is how the minimap looked for me when I tried to start it minimized without having a transition from maximized first - Leaflet gets confused about how large the map pane actually is and sizes itself wrongly. That's why I had to start it maximized and then minimize it at once. If I had to guess, I'd say maybe something about one of the other plugins or MMPro  makes the CSS transition happen too fast, or maybe it's just that so many things are initialising at the same time that the CSS transition is already under way before Leaflet geta around to initialising the minimap. Try increasing the CSS transition time to something really long and see if that makes a diference in how it behaves.

**Comment by robertharm** [comment]
thanks for your feedback! increasing CSS transition times didnt really have an effect unfortunately. I tried to use leaflet map events (on('load')...) for example but this didnt work either. So I used a (rather dirty) workaround and wrapped the minimap code for mobile devices (wp_is_mobile()-WordPress function) in a setTimeout()-function, adding the minimap control 1 second pause. So at least for now it works in 9 out of 10 tries. We will continue looking for a better solution here though....
