### ISSUE TITLE
Different minimap from primary map?

### ISSUE THREAD

**Issue by tiagomoucho3** [Norkart/Leaflet-MiniMap#132]
I have a non-geographical map (League of Legends Summoner's Rift) as my primary map. It is a screenshot of the map in-game. Now I added this plugin to mimic the minimap represented in the game (The image is different from the primary map, as is its scale). 

Is there a way to just center the image in the minimap to fit the box and represent that area in the primary map even if they are at different scales and bounds?

The primary map image is 2157x2158 and the minimap is 512x512. The bounds must also be different because of the margin of both images and because I use Riot API to get champions position to add them as markers which the points are in a different scale.

This is my code:

    /* Bounds definition */
    var bounds = [[-133,-169], [2303, 2283]];
	var mmbounds = [[-120,-120], [14870, 14980]];

	/* Map Setup */
	var map = L.map('map', {
		crs: L.CRS.Simple,
		minZoom: -2,
		maxZoom: 0.4,
		maxBounds: bounds,
		maxBoundsViscosity: 1.0
	});

	/* Add image to map */
	var image = L.imageOverlay('../images/LoLSummonerRiftv2EyeCandy.png', bounds).addTo(map);
	map.fitBounds(bounds);

	/* Minimap setup */
	var mmLayer = new L.TileLayer('../images/summonerRiftMiniMap.png', {noWrap: true, maxBounds: mmbounds});
	var miniMap = new L.Control.MiniMap(mmLayer, {toggleDisplay: true, width: 200, height: 200}).addTo(map);

Here's a screenshot of my application at the moment:
[https://imgur.com/a/doZrb](url)

Thanks for your time and attention!

**Comment by robpvn** [comment]
I've done some experiments at https://jsfiddle.net/954kxuLu/ . The main issue was that the main and mini map both needed to have the same CRS to make sense of each other, and Imageoverlay on the minimap as well. It's still a bit wrong, I think that's probably because the main and mini map have different sizes in pixels. Try enlarging the minimap image so that they're the same size, that might help. 

Aprat from that, this is not the intended use case for the minimap, so I can't make any guarantees. ;-)

**Comment by tiagomoucho3** [comment]
Thanks robpvn! I got it working. Enlarging the minimap really did the trick :)
