### ISSUE TITLE
Translation strings

### ISSUE THREAD

**Issue by lokal-profil** [Norkart/Leaflet-MiniMap#89]
Is there a performance reason for not being able to set `hideText`/`showText` as options rather than having to override them in a subclass?

Asking since i18n by passing-as-an-option seems to be standard among the Leaflet controls I've encountered.

**Comment by robpvn** [comment]
Not any real big reason, no. It was just the way the original contributor did it  way back when. I see that there is a [https://github.com/yohanboniface/Leaflet.i18n](Leaflet.i8n) plugin out now though, so it might be worth looking at that, I suppose. It's not real high up on my priority list since we only have two strings, but pull reqs are welcome.

**Comment by lokal-profil** [comment]
I'll happily put together a PR for it. Would the existing subclass method still be desired? I.e. need a patch be backwards compatible when it comes to this?

**Comment by robpvn** [comment]
Nah, since we never really had more than one translation added it won't matter to me if we make this a breaking change. I'll just bump the version number and be happy with that.
