### ISSUE TITLE
Fix a minimum size for the focus square ? 

### ISSUE THREAD

**Issue by damiendevienne** [Norkart/Leaflet-MiniMap#98]
Hello, 
I was wondering if it was possible to set a minimum size for the red square that indicates on the minimap where we are. It becomes invisible when ```zoomLevelFixed``` is set to a small value (`z`) , and when I zoom to, let's say, `z + 7`. 
Also, I didn't find where to change the color of this square. 
Thanks a lot !

**Comment by robpvn** [comment]
I'd say that with the current architecture, there isn't any way of doing what you ask, because the aiming rectangle simply shows the bounds of what you are looking at on the main map. Changing it would mean some rather unpleasant calculations and changes to how things work, so I don't want to do it. In general I would say you should avoid this issue by thinking over what zoomlevel you want to fix it at and how far in the user should be allowed to zoom. 

On your second question I do have a positive answer: Look under "Available Options" in the readme and check out `aimingRectOptions` and `shadowRectOptions`. By making the lines thicker and the colour stronger, it should be more visible.

**Comment by robpvn** [comment]
See this example for custom rectangles: https://github.com/Norkart/Leaflet-MiniMap/blob/master/example/example_customRects.html
